"""
Renders a human-readable Python-source PREVIEW of a compiled model --
"view generated code" transparency panel in the wizard UI, and a starting
point for a user who wants to graduate a model out of the wizard into a
real applications/<name>/ folder (see PLUGIN_GUIDE.md).

SECURITY NOTE, worth restating (see equation_parser.py/generic_plant.py
for the full reasoning): the text this module produces is NEVER executed
by the wizard. The app always runs models via generic_plant.py's closures
(built directly from parsed sympy expression trees), not by exec'ing this
preview text. This module exists purely for display/copy-out -- even so,
the arithmetic it prints comes from sympy's own printer applied to the
ALREADY-PARSED, ALREADY-WHITELISTED expression tree (never the user's raw
string spliced directly into a file), so what's shown is exactly what was
validated, not a re-interpretation of unvalidated text.

Output deliberately mirrors the hand-written style of
applications/dynamic_pricing/ and applications/duopoly_pricing/ (same
Euler-Maruyama dynamics.py structure, same DynamicsFn/MeasurementFn/
CostFn signatures) so a user comparing the two would recognize the shape
immediately.
"""

from __future__ import annotations

from wizard.equation_parser import parse_equation
from wizard.schema import ModelConfig


def _format_expr(text: str, all_names: list[str]) -> str:
    """Returns the canonical string form of an already-validated equation,
    or the raw text with a comment flag if it doesn't currently parse
    (e.g. mid-edit in the wizard) -- this preview must never raise just
    because the model isn't finished yet."""
    result = parse_equation(text, all_names)
    if result.ok:
        return str(result.expr)
    return f"{text}  # NOTE: does not currently parse ({result.error})"


def generate_constants_source(config: ModelConfig) -> str:
    lines = [
        '"""',
        f"Constants for '{config.name}', generated by the wizard.",
        '"""',
        "from dataclasses import dataclass, field",
        "import numpy as np",
        "",
        "",
        "@dataclass",
        "class GeneratedConstants:",
    ]
    if config.parameters:
        lines.append("    prior: np.ndarray = field(default_factory=lambda: np.array([")
        for p in config.parameters:
            lines.append(f"        {p.prior_guess!r},  # {p.name}")
        lines.append("    ]))")
    else:
        lines.append("    prior: np.ndarray = field(default_factory=lambda: np.zeros(0))")
    for c in config.constants:
        lines.append(f"    {c.name}: float = {c.value!r}")
    return "\n".join(lines) + "\n"


def generate_continuous_dynamics_source(config: ModelConfig) -> str:
    all_names = config.all_defined_names()
    lines = [
        '"""',
        f"Continuous-time dynamics for '{config.name}', generated by the wizard.",
        "",
        "STATE VECTOR:",
    ]
    for i, s in enumerate(config.states):
        lines.append(f"    x{i + 1} = {s.name}" + (f"  ({s.label})" if s.label else ""))
    lines.append("ACTION VECTOR:")
    for j, a in enumerate(config.actions):
        lines.append(f"    u{j + 1} = {a.name}" + (f"  ({a.label})" if a.label else ""))
    if config.parameters:
        lines.append("UNKNOWN PARAMETERS (estimated online):")
        for k, p in enumerate(config.parameters):
            lines.append(f"    p{k + 1} = {p.name}" + (f"  ({p.label})" if p.label else ""))
    lines += ['"""', "", "import numpy as np", "", ""]
    lines.append("def continuous_dynamics(dt, xa, u, constants, augment_states, u_lims,")
    lines.append("                          u_lim_method):")
    for i, s in enumerate(config.states):
        expr_str = _format_expr(config.dynamics.get(s.name, "0"), all_names)
        lines.append(f"    # d({s.name})/dt = {expr_str}")
    lines.append("    ...  # see generic_plant.make_continuous_dynamics_fn for the")
    lines.append("    ...  # actual generic implementation this preview mirrors")
    return "\n".join(lines) + "\n"


def generate_measurement_source(config: ModelConfig) -> str:
    all_names = config.all_defined_names()
    lines = [
        '"""',
        f"Measurement model for '{config.name}', generated by the wizard.",
        '"""',
        "",
        "def measurement(dt, xa, u, constants, v, noise_index, augment_states,",
        "                  v_from_filter):",
    ]
    for m in config.measurement:
        expr_str = _format_expr(m.expression, all_names)
        lines.append(f"    # {m.name} = {expr_str}   (noise scale = {m.noise_scale})")
    lines.append("    ...  # see generic_plant.make_measurement_fn for the actual")
    lines.append("    ...  # generic implementation this preview mirrors")
    return "\n".join(lines) + "\n"


def generate_cost_source(config: ModelConfig) -> str:
    all_names = config.all_defined_names()
    running_str = _format_expr(config.cost.running, all_names)
    terminal_str = _format_expr(config.cost.terminal, all_names)
    lines = [
        '"""',
        f"Cost function for '{config.name}', generated by the wizard.",
        "",
        f"running cost  = {running_str}",
        f"terminal cost = {terminal_str}",
        '"""',
        "",
        "def cost(xa, u, tracking_trajectory, u_lims, u_lim_method, constants):",
        "    ...  # see generic_plant.make_cost_fn for the actual generic",
        "    ...  # implementation this preview mirrors (zeroes NaN-marked",
        "    ...  # terminal control columns, then evaluates the terminal",
        "    ...  # expression there instead of the running one)",
    ]
    return "\n".join(lines) + "\n"


def generate_all_previews(config: ModelConfig) -> dict[str, str]:
    """Returns {display filename: source text} for every generated file
    -- what the wizard's 'View generated code' panel shows/offers to
    copy. Never raises: an incomplete or currently-invalid config just
    produces previews with inline '# NOTE: does not currently parse'
    flags rather than failing to render at all."""
    return {
        "constants.py": generate_constants_source(config),
        "continuous_dynamics.py": generate_continuous_dynamics_source(config),
        "measurement.py": generate_measurement_source(config),
        "cost.py": generate_cost_source(config),
    }
